### ISSUE TITLE
rolling with mutlivariate uts

### ISSUE THREAD

**Issue by Courvoisier13** [andreas50/utsOperators#1]
Hi @andreas50 

thank you for these packages, they are very promising and super fast. 

Do you if there is a workaround to do a rolling_apply with a multivariate uts? Say weighted.mean function with inputs x and w ?

thanks

**Comment by andreas50** [comment]
Hi,

I have written such a function (called "capply", for cross-sectional apply), but in the end decided to leave it out of the package for now, because the documentation would have been multiple times longer than the code and I wasn't happy with the complexity.

Some of the issues are:
-) What should the observation time points of the output be? The union of observation times of the input, some regular spacing, or custom provided times?
-) Should the calculation begin at the first or last initial observation time of the individual time series, or at some other time? And when should the calculation end?
-) How/if to recycle optional arguments (in your case, the vector "w") for the function to be applied? For example, should the j-th iteration of the for-loop calculate FUN(x[[j]] w) or FUN(x[[j]] w[j])?

If you are interested, I can share the version I have written, but my guess is that a tailored version for a weighted mean would be quick to write and be much shorter.

Cheers, Andreas

**Comment by Courvoisier13** [comment]
I see, it would be an issue if the variables were asynchronous. I was thinking of irregular obs but synchronous.
I was thinking more along the lines of rolling_apply, but for mutivariate and they are all observed at the same times. You're right, it's better to rebuild the function.

**Comment by andreas50** [comment]
For the synchronous case, `do.call("+", mapply(x, w, FUN="*"))` should do what you are looking for.

**Comment by Courvoisier13** [comment]
my obs are irregular but synchronous (the variables come at the same time, but not at uniform observations). And i want time based rolling averages, so for example going back 1 week with intraday obs. The function above needs to be filter over that period, observation by observation, so highly inefficient. Your rolling_apply seems to do it right. I compared the results and they match so that's good.
